app:
  security:
    jwt:
      secret-key: "dGVzdF9zZWNyZXRfa2V5X2Zvcl9kZXZlbG9wbWVudF9vbmx5X2RvX25vdF91c2VfaW5fcHJvZHVjdGlvbg=="
      token-expiration-ms: 3600000  # 1 hour
      refresh-expiration-ms: 86400000  # 24 hours
      token-prefix: "Bearer "
      header-name: "Authorization"