app:
  security:
    jwt:
      secret-key: "dGVzdF9zZWNyZXRfa2V5X2Zvcl9kZXZlbG9wbWVudF9vbmx5X2RvX25vdF91c2VfaW5fcHJvZHVjdGlvbg=="
      token-expiration-ms: 3600000
      refresh-expiration-ms: 86400000
      token-prefix: "Bearer "
      header-name: "Authorization"
      allowed-origins:
        - "http://localhost:3000"
        - "http://127.0.0.1:5500"
        - ""



  